### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by FWeissenb** [tvaddonsco/plugin.program.indigo#14]
If I want to start I get an error.

If I look to my logs I can see this: 
```
95 T:1460462464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'lower'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.program.indigo/default.py", line 15, in <module>
                                                import installer
                                              File "/storage/.kodi/addons/plugin.program.indigo/installer.py", line 53, in <module>
                                                kodi_url = "http://mirrors.kodi.tv/addons/" + kodi.get_codename().lower() + '/'
                                            AttributeError: 'NoneType' object has no attribute 'lower'
                                            -->End of Python script error report<--
```

I have the newest Milhouse nightly build on Rasp3 and Indigo 4.0.12

**Comment by tvaddonsco** [comment]
When you are trying to start what exactly? @FWeissenb

**Comment by tvaddonsco** [comment]
Are you still having this issue? @FWeissenb

**Comment by tvaddonsco** [comment]
Please provide a full error log! @FWeissenb
